services:
  - type: web
    name: code-architect-api
    runtime: python-3.11.7
    buildCommand: pip install --only-binary=:all: -r backend/requirements.txt
    startCommand: cd backend && gunicorn -w 4 -b 0.0.0.0:$PORT main:app
